DROP TABLE IF EXISTS STUDENTS,TEACHERS,RATE,TEACHREFEE;

CREATE TABLE STUDENTS (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    EMAIL TEXT UNIQUE,
    PROFILE TEXT,
    T_ID INTEGER,
    FOREIGN KEY (T_ID) REFERENCES TEACHERS(ID) 
);

CREATE TABLE TEACHERS (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    EMAIL TEXT UNIQUE,
    PROFILE TEXT
);

CREATE TABLE RATE (
    S_ID INTEGER,
    T_ID INTEGER,
    RATE DECIMAL(2,1),
    FOREIGN KEY (S_ID) REFERENCES STUDENTS(ID),
    FOREIGN KEY (T_ID) REFERENCES TEACHERS(ID),
    PRIMARY KEY (S_ID,T_ID)
);

CREATE TABLE TEACHERFEE ( 
    T_ID INTEGER,
    FEE INTEGER,
    FOREIGN KEY (T_ID) REFERENCES TEACHERS(ID),
    PRIMARY KEY (T_ID)
);



